---
name: CI

on:
  push:
    branches: main
  pull_request:

env:
  JAVA_VERSION: adopt@1.8.0-272

jobs:

  microsite:
    name: microsite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Cache Coursier
        uses: actions/cache@v2
        with:
          path: ~/.cache/coursier
          key: coursier-microsite-${{ hashFiles('**/build.sbt') }}
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: sbt-microsite-${{ hashFiles('**/build.sbt') }}
      - name: Build microsite
        run: sbt site/makeSite

  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: sbt-scalafmt-${{ hashFiles('**/project/plugins.sbt') }}
      - name: Check sbt files
        run: sbt scalafmtSbtCheck
      - name: Check scala files
        run: sbt scalafmtCheckAll

  validate:
    strategy:
      fail-fast: false
      matrix:
        scala:
          - 2.13.3
          - 2.12.13
    name: compile and test ${{ matrix.scala }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Cache Coursier
        uses: actions/cache@v2
        with:
          path: ~/.cache/coursier
          key: coursier-${{ hashFiles('**/build.sbt') }}
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}
      - name: Compile
        run: sbt ++${{ matrix.scala }} clean compile test:compile
      - name: Test
        run: sbt ++${{ matrix.scala }} test

  changelog:
    name: changelog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install python-kacl
        run: pip install python-kacl
      - name: Verify CHANGELOG.md
        run: kacl-cli --config .github/.kacl.yaml verify
