name: CI
on: push
env:
  CI: true
  JAVA_VERSION: adopt@v1.11
jobs:
  formatting:
    name: Check scalafmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Check sbt
        run: sbt scalafmtSbtCheck
      - name: Check scala
        run: sbt scalafmtCheckAll
  validate:
    name: Compile & Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v5
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: sbt-coursier-cache
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}
      - name: Compile
        run: sbt compile test:compile
      - name: Test
        run: sbt test
