---
name: CI

on:
  push:
    branches: master
  pull_request:

env:
  JAVA_VERSION: adopt@v1.11

jobs:

  format:
    name: format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-scalafmt-${{ hashFiles('**/project/plugins.sbt') }}
      - name: Check sbt files
        run: sbt scalafmtSbtCheck
      - name: Check scala files
        run: sbt scalafmtCheckAll

  validate:
    name: compile and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: coursier-${{ hashFiles('**/build.sbt') }}
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}
      - name: Compile
        run: sbt clean compile test:compile
      - name: Test
        run: sbt test
