---
name: Release
on:
  push:
    branches: master
    tags: '*'

env:
  JAVA_VERSION: adopt@v1.11

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - uses: olafurpg/setup-gpg@v2
      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: coursier-${{ hashFiles('**/build.sbt') }}
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-${{ hashFiles('**/build.sbt') }}
      - name: Publish
        run: sbt ci-release
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}

  gh-release:
    name: Create Release ${{ github.ref }}
    runs-on: ubuntu-latest
    if: github.event_name == 'tags'
    needs: release
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get vars
        id: vars
        run: |
          echo ::set-output name=tag::${GITHUB_REF/refs\/tags\//}
          echo ::set-output name=date::$(date +%F)
          echo ::set-output name=version::${GITHUB_REF/refs\/tags\/v/}
      - name: Get date
        id: date
        run: echo ::set-output name=value::$(date +%F)
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.vars.outputs.tag }}
          release_name: ${{ steps.vars.outputs.tag }}
          body: Full changelog: https://github.com/cats4scala/cats-process/blob/master/CHANGELOG.md#${{ steps.vars.outputs.version }}---${{ steps.vars.outputs.date }}
          draft: false
          prerelease: false

  publish-microsite:
    name: publish microsite
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - uses: olafurpg/setup-scala@v7
        with:
          java-version: ${{ env.JAVA_VERSION }}
      - name: Cache Coursier
        uses: actions/cache@v1
        with:
          path: ~/.cache/coursier
          key: coursier-microsite-${{ hashFiles('**/build.sbt') }}
      - name: Cache SBT
        uses: actions/cache@v1
        with:
          path: ~/.sbt
          key: sbt-microsite-${{ hashFiles('**/build.sbt') }}
      - name: Build
        run: sbt site/makeSite
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site/target/site
          commit_message: ${{ github.event.head_commit.message }}
